### ISSUE TITLE
batch size该如何理解呢？

### ISSUE THREAD

**Issue by jiahe224** [unclestrong/DeepLearning_LHY21_Notes#1]
从上图看，是每次更新用几个batch，但从下图看，好像是每个batch里有多少条数据

![image](https://user-images.githubusercontent.com/35186992/111754646-3397de80-88d3-11eb-8269-0bc37ebe09bc.png)

![image](https://user-images.githubusercontent.com/35186992/111755627-452db600-88d4-11eb-945a-bebcd7b5e3ef.png)

**Comment by unclestrong** [comment]
其实意思是一样的 因为你数据集里的 总数据数量是一定的 你分的batch少 每个batch里数据就多 分的batch多 每个batch里的数据就多
