### ISSUE TITLE
图片失效不能查看了，大佬

### ISSUE THREAD

**Issue by skyboxle** [unclestrong/DeepLearning_LHY21_Notes#11]
大佬可以更新一下图片嘛

**Comment by Jace-Yang** [comment]
同求！

**Comment by unclestrong** [comment]
已经替换为PDF

**Comment by skyboxle** [comment]
谢谢大佬，麻烦你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "unclestrong/DeepLearning_LHY21_Notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [unclestrong/DeepLearning_LHY21_Notes] 图片失效不能查看了，大佬 (Issue #11)





 
已经替换为PDF
